const BASIC_INFO = '基本信息';
const EDU_BACKGROUND = '教育背景';
const INTERN_EXPERIENCE = '实习经历';
const PROJECTS_EXPERIENCE = '项目经历';
export {BASIC_INFO, EDU_BACKGROUND, INTERN_EXPERIENCE, PROJECTS_EXPERIENCE};

const ADD_ITEM='ADD_ITEM';
const EDIT_ITEM='EDIT_ITEM';
const ON_REMOVE='ON_REMOVE';
